# Generated by Django 4.2 on 2023-04-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-date'], 'verbose_name': 'Data'},
        ),
    ]
